@host=http://localhost

@port=3000

@endpoint=api/notes

@contentType= application/json

@token = eyJhbGciOiJFUzI1NiIsImtpZCI6ImJjYjU2NGU4LTJjM2QtNGU2Ni04ZjQ5LTFiNmUxYmQ2NGQ0MCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3VvZXpyZGtlYWx5dm53bmV5dXF3LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJhNGNjMWNiMC0zNTljLTQ4MDUtYjNhYi1mYjk0YTE5MjkyOTQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY4MDk4OTIyLCJpYXQiOjE3NjgwOTUzMjIsImVtYWlsIjoiY2hhbGxlbmdlQHRlc3QuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NjgwOTUzMjJ9XSwic2Vzc2lvbl9pZCI6IjliOWNlNjY0LWZiYTgtNDI0ZC1hNWI4LWRhYWM4NGI4ZDY5MCIsImlzX2Fub255bW91cyI6ZmFsc2V9.9dkFXyDjWBWhqQzUtkN6t4eiwpNqaRzVaTMfS81e6c78ORFcqUUSp-23ORnp5RC3owypbfYZHcHblUeaeuzy7Q

### get all notes
GET {{host}}:{{port}}/{{endpoint}}
Content-Type: {{contentType}}
Authorization: Bearer {{token}}